name: Publish Package to NPM
on:
  push:
    branches:
      - master
#  release:
#    types: [published]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Depdencies
        run: yarn
      - name: Test
        run: yarn test


  publish-npm:
    name: Publish
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          yarn
          yarn build
          rm -rf .github
          rm -rf src
          rm -rf .prettierignore
          rm -rf .prettierrc
          rm -rf babel.config.js
          rm -rf jest.config.js
          rm -rf tsconfig.json
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
