name: Publish Package to NPM
on:
  push:
    branches:
      - master
#  release:
#    types: [published]
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Depdencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test


  publish-npm:
    name: Publish
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          yarn
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
