name: Pull Request

on:
  pull_request_target:
    branches:
      - master

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn
      - name: Prettier Check
        run: yarn prettier:check
      - name: Build
        run: yarn build
      - name: Test with Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2